version: "3.9"
services:
  postgres_todolist:
    image: postgres:15.1-alpine
    container_name: postgres_todolist
    environment:
      POSTGRES_DB: "todolist"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "postgre$"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: unless-stopped
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "8765:5432"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_todolist
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
